name: Sample Workflow
on: [push]
Jobs:
  explore-first-github-workflow:
    runs-on: unbuntu-latest
    steps: 
      - run: echo "this job was automatically triggered by a ${{ github.event_name }} event"
      - run: echo "this job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "the name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code 
        uses: action/checkout@v2
      - run: echo "the ${{ github.repository }} repository gas been cloned to the runner."
      - run: echo "the workflow is ready to test your code on the runner."
      - name: list files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "this job's status is ${{ job.status }}."
      
